yolo_model:

  config_file:
    name: yolov3-tiny-traffic.cfg
  weight_file:
    name: yolov3-tiny-traffic.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - green
      - left
      - red
      - stop
      - straight
